import { GoOrganization } from "react-icons/go";
import {
  LockIcon,
  FiHome,
  GoInbox,
  FiCalendar,
  LuCodesandbox,
  PiAddressBook,
  IoIosHelpCircleOutline,
  FiSettings,
} from "../Components/Generals/Icons";

export const Organization = [
  { value: "Tripath Logistics", label: "Tripath Logistics" },
  { value: "Tripath Pvt Limit", label: "Tripath Pvt Limit" },
  { value: "Sea post Pvt Limit", label: "Sea Post Pvt Limit" },
];

export const FILING_MODES = [
  { value: "All", label: "All" },
  { value: "Air", label: "Air" },
  { value: "Road", label: "Road" },
  { value: "Sea", label: "Sea" },
];

export const MODES = [
  { value: "All", label: "All" },
  { value: "Air", label: "Air" },
  { value: "Road", label: "Road" },
  { value: "Sea", label: "Sea" },
];

export const PORTS = [
  { value: "All", label: "All" },
  { value: "Port A", label: "Port A" },
  { value: "Port B", label: "Port B" },
  { value: "Port C", label: "Port C" },
];

export const SB_TYPES = [
  { value: "All", label: "All" },
  { value: "Port A", label: "Port A" },
  { value: "Port B", label: "Port B" },
  { value: "Port C", label: "Port C" },
];

export const ACTIVE_OPTIONS = [
  { value: "All", label: "All" },
  { value: "Yes", label: "Yes" },
  { value: "No", label: "No" },
];
export const SHOW_OPTIONS = ["All", "Live Jobs", "Closed Jobs"];

export const CUSTOM_HOUSES = [
  { value: "All", label: "All" },
  { value: "Custom House A", label: "Custom House A" },
  { value: "Custom House B", label: "Custom House B" },
  { value: "Custom House C", label: "Custom House C" },
];

export const tableHeaders = [
  {
    id: "lock",
    label: "Lock",
    // icon: <LockIcon sx={{ fontSize: 18, color: "gray" }} />,
  },
  { id: "date", label: "Date" },
  { id: "jobId", label: "Job ID" },
  { id: "trackingNo", label: "Tracking No" },
  { id: "exporter", label: "Exporter" },
  { id: "mode", label: "Mode" },
  { id: "customHouse", label: "Custom House" },
  { id: "bankDealer", label: "Bank Dealer" },
  { id: "actions", label: "Actions" },
  { id: "invoiceNo", label: "Invoice No" },
  { id: "invoiceDate", label: "Invoice Date" },
  { id: "itemCount", label: "Items Count" },
  { id: "containerNo", label: "Container No" },
  { id: "grossWeight", label: "Gross Weight" },
  { id: "netWeight", label: "Net Weight" },
  { id: "packageCount", label: "Packages" },
  { id: "vesselName", label: "Vessel Name" },
  { id: "remarks", label: "Remarks" },
];

export const tableRows = [
  {
    date: "01/12/2001",
    jobId: "TLPL/SE/EXP/00101/25-26",
    trackingNo: "30-0000080001",
    exporter: "Exporter 1",
    mode: "Sea",
    customHouse: "Bangalore ICD",
    bankDealer: "ICICI Bank",
    invoiceNo: "INV001",
    invoiceDate: "01/12/2001",
    itemCount: 10,
    containerNo: "CONT001",
    grossWeight: "1000kg",
    netWeight: "950kg",
    packageCount: 40,
    vesselName: "Vessel 1",
    remarks: "Ready",
  },
  {
    date: "02/12/2001",
    jobId: "TLPL/SE/EXP/00102/25-26",
    trackingNo: "30-0000080002",
    exporter: "Exporter 2",
    mode: "Air",
    customHouse: "Mumbai Air Cargo",
    bankDealer: "HDFC Bank",
    invoiceNo: "INV002",
    invoiceDate: "02/12/2001",
    itemCount: 12,
    containerNo: "CONT002",
    grossWeight: "1020kg",
    netWeight: "970kg",
    packageCount: 42,
    vesselName: "Vessel 2",
    remarks: "Pending",
  },
  {
    date: "03/12/2001",
    jobId: "TLPL/SE/EXP/00103/25-26",
    trackingNo: "30-0000080003",
    exporter: "Exporter 3",
    mode: "Road",
    customHouse: "Delhi ICD",
    bankDealer: "Axis Bank",
    invoiceNo: "INV003",
    invoiceDate: "03/12/2001",
    itemCount: 8,
    containerNo: "CONT003",
    grossWeight: "950kg",
    netWeight: "900kg",
    packageCount: 35,
    vesselName: "Vessel 3",
    remarks: "Ready",
  },
  {
    date: "04/12/2001",
    jobId: "TLPL/SE/EXP/00104/25-26",
    trackingNo: "30-0000080004",
    exporter: "Exporter 4",
    mode: "Sea",
    customHouse: "Chennai Port",
    bankDealer: "Yes Bank",
    invoiceNo: "INV004",
    invoiceDate: "04/12/2001",
    itemCount: 14,
    containerNo: "CONT004",
    grossWeight: "1100kg",
    netWeight: "1050kg",
    packageCount: 48,
    vesselName: "Vessel 4",
    remarks: "Hold",
  },
  {
    date: "05/12/2001",
    jobId: "TLPL/SE/EXP/00105/25-26",
    trackingNo: "30-0000080005",
    exporter: "Exporter 5",
    mode: "Air",
    customHouse: "Hyderabad Air Cargo",
    bankDealer: "SBI",
    invoiceNo: "INV005",
    invoiceDate: "05/12/2001",
    itemCount: 9,
    containerNo: "CONT005",
    grossWeight: "980kg",
    netWeight: "920kg",
    packageCount: 37,
    vesselName: "Vessel 5",
    remarks: "Ready",
  },
  {
    date: "06/12/2001",
    jobId: "TLPL/SE/EXP/00106/25-26",
    trackingNo: "30-0000080006",
    exporter: "Exporter 6",
    mode: "Road",
    customHouse: "Ahmedabad ICD",
    bankDealer: "ICICI Bank",
    invoiceNo: "INV006",
    invoiceDate: "06/12/2001",
    itemCount: 11,
    containerNo: "CONT006",
    grossWeight: "1050kg",
    netWeight: "1000kg",
    packageCount: 43,
    vesselName: "Vessel 6",
    remarks: "Pending",
  },
  {
    date: "07/12/2001",
    jobId: "TLPL/SE/EXP/00107/25-26",
    trackingNo: "30-0000080007",
    exporter: "Exporter 7",
    mode: "Sea",
    customHouse: "Kolkata Port",
    bankDealer: "HDFC Bank",
    invoiceNo: "INV007",
    invoiceDate: "07/12/2001",
    itemCount: 13,
    containerNo: "CONT007",
    grossWeight: "1120kg",
    netWeight: "1070kg",
    packageCount: 50,
    vesselName: "Vessel 7",
    remarks: "Ready",
  },
  {
    date: "08/12/2001",
    jobId: "TLPL/SE/EXP/00108/25-26",
    trackingNo: "30-0000080008",
    exporter: "Exporter 8",
    mode: "Air",
    customHouse: "Cochin Port",
    bankDealer: "Axis Bank",
    invoiceNo: "INV008",
    invoiceDate: "08/12/2001",
    itemCount: 10,
    containerNo: "CONT008",
    grossWeight: "1000kg",
    netWeight: "950kg",
    packageCount: 40,
    vesselName: "Vessel 8",
    remarks: "In Transit",
  },
  {
    date: "09/12/2001",
    jobId: "TLPL/SE/EXP/00109/25-26",
    trackingNo: "30-0000080009",
    exporter: "Exporter 9",
    mode: "Road",
    customHouse: "Nagpur ICD",
    bankDealer: "Yes Bank",
    invoiceNo: "INV009",
    invoiceDate: "09/12/2001",
    itemCount: 15,
    containerNo: "CONT009",
    grossWeight: "1150kg",
    netWeight: "1100kg",
    packageCount: 55,
    vesselName: "Vessel 9",
    remarks: "Ready",
  },
  {
    date: "10/12/2001",
    jobId: "TLPL/SE/EXP/00110/25-26",
    trackingNo: "30-0000080010",
    exporter: "Exporter 10",
    mode: "Sea",
    customHouse: "Bangalore ICD",
    bankDealer: "SBI",
    invoiceNo: "INV010",
    invoiceDate: "10/12/2001",
    itemCount: 16,
    containerNo: "CONT010",
    grossWeight: "1160kg",
    netWeight: "1110kg",
    packageCount: 57,
    vesselName: "Vessel 10",
    remarks: "Cleared",
  },
  {
    date: "01/12/2001",
    jobId: "TLPL/SE/EXP/00101/25-26",
    trackingNo: "30-0000080001",
    exporter: "Exporter 1",
    mode: "Sea",
    customHouse: "Bangalore ICD",
    bankDealer: "ICICI Bank",
    invoiceNo: "INV001",
    invoiceDate: "01/12/2001",
    itemCount: 10,
    containerNo: "CONT001",
    grossWeight: "1000kg",
    netWeight: "950kg",
    packageCount: 40,
    vesselName: "Vessel 1",
    remarks: "Ready",
  },
  {
    date: "02/12/2001",
    jobId: "TLPL/SE/EXP/00102/25-26",
    trackingNo: "30-0000080002",
    exporter: "Exporter 2",
    mode: "Air",
    customHouse: "Mumbai Air Cargo",
    bankDealer: "HDFC Bank",
    invoiceNo: "INV002",
    invoiceDate: "02/12/2001",
    itemCount: 12,
    containerNo: "CONT002",
    grossWeight: "1020kg",
    netWeight: "970kg",
    packageCount: 42,
    vesselName: "Vessel 2",
    remarks: "Pending",
  },
  {
    date: "03/12/2001",
    jobId: "TLPL/SE/EXP/00103/25-26",
    trackingNo: "30-0000080003",
    exporter: "Exporter 3",
    mode: "Road",
    customHouse: "Delhi ICD",
    bankDealer: "Axis Bank",
    invoiceNo: "INV003",
    invoiceDate: "03/12/2001",
    itemCount: 8,
    containerNo: "CONT003",
    grossWeight: "950kg",
    netWeight: "900kg",
    packageCount: 35,
    vesselName: "Vessel 3",
    remarks: "Ready",
  },
  {
    date: "04/12/2001",
    jobId: "TLPL/SE/EXP/00104/25-26",
    trackingNo: "30-0000080004",
    exporter: "Exporter 4",
    mode: "Sea",
    customHouse: "Chennai Port",
    bankDealer: "Yes Bank",
    invoiceNo: "INV004",
    invoiceDate: "04/12/2001",
    itemCount: 14,
    containerNo: "CONT004",
    grossWeight: "1100kg",
    netWeight: "1050kg",
    packageCount: 48,
    vesselName: "Vessel 4",
    remarks: "Hold",
  },
  {
    date: "05/12/2001",
    jobId: "TLPL/SE/EXP/00105/25-26",
    trackingNo: "30-0000080005",
    exporter: "Exporter 5",
    mode: "Air",
    customHouse: "Hyderabad Air Cargo",
    bankDealer: "SBI",
    invoiceNo: "INV005",
    invoiceDate: "05/12/2001",
    itemCount: 9,
    containerNo: "CONT005",
    grossWeight: "980kg",
    netWeight: "920kg",
    packageCount: 37,
    vesselName: "Vessel 5",
    remarks: "Ready",
  },
  {
    date: "06/12/2001",
    jobId: "TLPL/SE/EXP/00106/25-26",
    trackingNo: "30-0000080006",
    exporter: "Exporter 6",
    mode: "Road",
    customHouse: "Ahmedabad ICD",
    bankDealer: "ICICI Bank",
    invoiceNo: "INV006",
    invoiceDate: "06/12/2001",
    itemCount: 11,
    containerNo: "CONT006",
    grossWeight: "1050kg",
    netWeight: "1000kg",
    packageCount: 43,
    vesselName: "Vessel 6",
    remarks: "Pending",
  },
  {
    date: "07/12/2001",
    jobId: "TLPL/SE/EXP/00107/25-26",
    trackingNo: "30-0000080007",
    exporter: "Exporter 7",
    mode: "Sea",
    customHouse: "Kolkata Port",
    bankDealer: "HDFC Bank",
    invoiceNo: "INV007",
    invoiceDate: "07/12/2001",
    itemCount: 13,
    containerNo: "CONT007",
    grossWeight: "1120kg",
    netWeight: "1070kg",
    packageCount: 50,
    vesselName: "Vessel 7",
    remarks: "Ready",
  },
  {
    date: "08/12/2001",
    jobId: "TLPL/SE/EXP/00108/25-26",
    trackingNo: "30-0000080008",
    exporter: "Exporter 8",
    mode: "Air",
    customHouse: "Cochin Port",
    bankDealer: "Axis Bank",
    invoiceNo: "INV008",
    invoiceDate: "08/12/2001",
    itemCount: 10,
    containerNo: "CONT008",
    grossWeight: "1000kg",
    netWeight: "950kg",
    packageCount: 40,
    vesselName: "Vessel 8",
    remarks: "In Transit",
  },
  {
    date: "09/12/2001",
    jobId: "TLPL/SE/EXP/00109/25-26",
    trackingNo: "30-0000080009",
    exporter: "Exporter 9",
    mode: "Road",
    customHouse: "Nagpur ICD",
    bankDealer: "Yes Bank",
    invoiceNo: "INV009",
    invoiceDate: "09/12/2001",
    itemCount: 15,
    containerNo: "CONT009",
    grossWeight: "1150kg",
    netWeight: "1100kg",
    packageCount: 55,
    vesselName: "Vessel 9",
    remarks: "Ready",
  },
  {
    date: "10/12/2001",
    jobId: "TLPL/SE/EXP/00110/25-26",
    trackingNo: "30-0000080010",
    exporter: "Exporter 10",
    mode: "Sea",
    customHouse: "Bangalore ICD",
    bankDealer: "SBI",
    invoiceNo: "INV010",
    invoiceDate: "10/12/2001",
    itemCount: 16,
    containerNo: "CONT010",
    grossWeight: "1160kg",
    netWeight: "1110kg",
    packageCount: 57,
    vesselName: "Vessel 10",
    remarks: "Cleared",
  },
  {
    date: "01/12/2001",
    jobId: "TLPL/SE/EXP/00101/25-26",
    trackingNo: "30-0000080001",
    exporter: "Exporter 1",
    mode: "Sea",
    customHouse: "Bangalore ICD",
    bankDealer: "ICICI Bank",
    invoiceNo: "INV001",
    invoiceDate: "01/12/2001",
    itemCount: 10,
    containerNo: "CONT001",
    grossWeight: "1000kg",
    netWeight: "950kg",
    packageCount: 40,
    vesselName: "Vessel 1",
    remarks: "Ready",
  },
  {
    date: "02/12/2001",
    jobId: "TLPL/SE/EXP/00102/25-26",
    trackingNo: "30-0000080002",
    exporter: "Exporter 2",
    mode: "Air",
    customHouse: "Mumbai Air Cargo",
    bankDealer: "HDFC Bank",
    invoiceNo: "INV002",
    invoiceDate: "02/12/2001",
    itemCount: 12,
    containerNo: "CONT002",
    grossWeight: "1020kg",
    netWeight: "970kg",
    packageCount: 42,
    vesselName: "Vessel 2",
    remarks: "Pending",
  },
  {
    date: "03/12/2001",
    jobId: "TLPL/SE/EXP/00103/25-26",
    trackingNo: "30-0000080003",
    exporter: "Exporter 3",
    mode: "Road",
    customHouse: "Delhi ICD",
    bankDealer: "Axis Bank",
    invoiceNo: "INV003",
    invoiceDate: "03/12/2001",
    itemCount: 8,
    containerNo: "CONT003",
    grossWeight: "950kg",
    netWeight: "900kg",
    packageCount: 35,
    vesselName: "Vessel 3",
    remarks: "Ready",
  },
  {
    date: "04/12/2001",
    jobId: "TLPL/SE/EXP/00104/25-26",
    trackingNo: "30-0000080004",
    exporter: "Exporter 4",
    mode: "Sea",
    customHouse: "Chennai Port",
    bankDealer: "Yes Bank",
    invoiceNo: "INV004",
    invoiceDate: "04/12/2001",
    itemCount: 14,
    containerNo: "CONT004",
    grossWeight: "1100kg",
    netWeight: "1050kg",
    packageCount: 48,
    vesselName: "Vessel 4",
    remarks: "Hold",
  },
  {
    date: "05/12/2001",
    jobId: "TLPL/SE/EXP/00105/25-26",
    trackingNo: "30-0000080005",
    exporter: "Exporter 5",
    mode: "Air",
    customHouse: "Hyderabad Air Cargo",
    bankDealer: "SBI",
    invoiceNo: "INV005",
    invoiceDate: "05/12/2001",
    itemCount: 9,
    containerNo: "CONT005",
    grossWeight: "980kg",
    netWeight: "920kg",
    packageCount: 37,
    vesselName: "Vessel 5",
    remarks: "Ready",
  },
  {
    date: "06/12/2001",
    jobId: "TLPL/SE/EXP/00106/25-26",
    trackingNo: "30-0000080006",
    exporter: "Exporter 6",
    mode: "Road",
    customHouse: "Ahmedabad ICD",
    bankDealer: "ICICI Bank",
    invoiceNo: "INV006",
    invoiceDate: "06/12/2001",
    itemCount: 11,
    containerNo: "CONT006",
    grossWeight: "1050kg",
    netWeight: "1000kg",
    packageCount: 43,
    vesselName: "Vessel 6",
    remarks: "Pending",
  },
  {
    date: "07/12/2001",
    jobId: "TLPL/SE/EXP/00107/25-26",
    trackingNo: "30-0000080007",
    exporter: "Exporter 7",
    mode: "Sea",
    customHouse: "Kolkata Port",
    bankDealer: "HDFC Bank",
    invoiceNo: "INV007",
    invoiceDate: "07/12/2001",
    itemCount: 13,
    containerNo: "CONT007",
    grossWeight: "1120kg",
    netWeight: "1070kg",
    packageCount: 50,
    vesselName: "Vessel 7",
    remarks: "Ready",
  },
  {
    date: "08/12/2001",
    jobId: "TLPL/SE/EXP/00108/25-26",
    trackingNo: "30-0000080008",
    exporter: "Exporter 8",
    mode: "Air",
    customHouse: "Cochin Port",
    bankDealer: "Axis Bank",
    invoiceNo: "INV008",
    invoiceDate: "08/12/2001",
    itemCount: 10,
    containerNo: "CONT008",
    grossWeight: "1000kg",
    netWeight: "950kg",
    packageCount: 40,
    vesselName: "Vessel 8",
    remarks: "In Transit",
  },
  {
    date: "09/12/2001",
    jobId: "TLPL/SE/EXP/00109/25-26",
    trackingNo: "30-0000080009",
    exporter: "Exporter 9",
    mode: "Road",
    customHouse: "Nagpur ICD",
    bankDealer: "Yes Bank",
    invoiceNo: "INV009",
    invoiceDate: "09/12/2001",
    itemCount: 15,
    containerNo: "CONT009",
    grossWeight: "1150kg",
    netWeight: "1100kg",
    packageCount: 55,
    vesselName: "Vessel 9",
    remarks: "Ready",
  },
  {
    date: "10/12/2001",
    jobId: "TLPL/SE/EXP/00110/25-26",
    trackingNo: "30-0000080010",
    exporter: "Exporter 10",
    mode: "Sea",
    customHouse: "Bangalore ICD",
    bankDealer: "SBI",
    invoiceNo: "INV010",
    invoiceDate: "10/12/2001",
    itemCount: 16,
    containerNo: "CONT010",
    grossWeight: "1160kg",
    netWeight: "1110kg",
    packageCount: 57,
    vesselName: "Vessel 10",
    remarks: "Cleared",
  }
];



export const fillingModes = ["ICEGATE", "Other", "BLRTRIPATH"];
export const fillingModes1 = ["ICEGATE", "Other", "BLRTRIPATH"];
export const transportModes = ["Air", "Sea", "Road"];
export const customHouses = [
  "Bangalore Air Cargo",
  "Mumbai Air Cargo",
  "Chennai Air Cargo",
  "Delhi Air Cargo",
  "Kolkata Air Cargo",
  "Hyderabad Air Cargo",
  "Ahmedabad Air Cargo",
  "Pune Air Cargo",
  "Jaipur Air Cargo",
  "Lucknow Air Cargo",
];
export const loadingPorts = [
  "Bangalore Air Cargo",
  "Chennai Port",
  "Mumbai Port",
  "Delhi Port",
  "Kolkata Port",
  "Hyderabad Port",
  "Ahmedabad Port",
  "Pune Port",
  "Jaipur Port",
  "Lucknow Port",
];
export const sbTypes = ["White - Free/DEEC", "Other"];

export const tabs = [
  { label: "Overview", id: "overview" },
  { label: "General", id: "general" },
  { label: "Entity", id: "entity" },
  { label: "SEZ info", id: "sez" },
  { label: "Shipment", id: "shipment" },
  { label: "Invoice", id: "invoice" },
  { label: "Product", id: "product" },
  { label: "Exch.Rate", id: "exchange" },
  { label: "eSanchit", id: "esanchit" },
  { label: "E-Docket", id: "edocket" },
  { label: "Requirement", id: "requirement" },
  { label: "ICEGATE", id: "icegate" },
  { label: "Customs", id: "customs" },
  { label: "Documents", id: "documents" },
  { label: "Charges", id: "charges" },
  { label: "Payments", id: "payments" },
  { label: "Tracking", id: "tracking" },
  { label: "History", id: "history" },
  { label: "Notes", id: "notes" },
  { label: "Settings", id: "settings" },
];
export const VISIBLE_TABS = 15;

export const Addexpertstab = [
  { label: "Overview", id: "overview" },
  { label: "Shipper", id: "shipper" },
  { label: "Consignee", id: "consignee" },
  { label: "Agent", id: "agent" },
  { label: "Services", id: "services" },
  { label: "Carrier", id: "carrier" },
  { label: "Reg", id: "reg" },
  { label: "Integrations", id: "integrations" },
  { label: "KYC", id: "kyc" },
  { label: "Notes", id: "notes" },
  { label: "History", id: "history" },
];

export const drawerWidth = 250;


export const organizations = [
  { label: "Softlink Global", value: "softlink" },
  { label: "Infosys", value: "infosys" },
  { label: "TCS", value: "tcs" },
  { label: "Wipro", value: "wipro" },
  { label: "HCL", value: "hcl" },
  { label: "IBM", value: "ibm" },
  { label: "Accenture", value: "accenture" },
  { label: "Capgemini", value: "capgemini" },
  { label: "Zoho", value: "zoho" },
  { label: "Tech Mahindra", value: "techmahindra" },
];
